# Generated by Django 4.2.30 on 2026-08-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='group_number',
            field=models.CharField(max_length=50),
        ),
    ]
